### PR TITLE
fix status, result, and state not updating

### PR DESCRIPTION
**Pull request by diablodale**
The logic used to see/parse the switch on/off status will not work with modern versions of Sonoff-Tasmota.
This fix has been tested and works against Sonoff-Tasmota v5.10, v5.11, and v5.11.1

Perhaps the format changed in the past and the groovy was not updated.
Do you know what caused you to use code like `def STATUS_PREFIX = "STATUS = "`? That text never occurs in the body in the modern tasmota.

### CODE REVIEW

**Comment by BrettSheleski** [comment]
I happened to see you forked my repo and made this commit.  This was a result of Tasmota being updated to send true JSON responses via the HTTP interface (see [Tasmota Issue #1363](https://github.com/arendst/Sonoff-Tasmota/issues/1363)).  I requested Tasmota to make this change due to in some cases SmartThings does not handle HTTP responses if neither application/json nor text/xml content type header is set.  (This is needed in a new/better set of SmartThings Device Handlers I plan on implementing)

Perhaps your solution could keep the old checks in an else-if statement for cases of using an older version of Tasmota?

**Comment by diablodale** [comment]
I don't mind doing that. Do you have a raw dump of whatever the old tasmota would send so I can code/test it? Or some way that I can determine what firmware you wrote the original code against so I can install/test against that firmware?

It is possible for me to reverse-eng the parsing code you wrote to integrate it. Though I prefer never to do that without testing it.

An alternative would be to take the new parsing/code, and require the modern tasmota. Groovy was broken with modern tasmota. I suspect the number of people that would download this new groovy yet not update their tasmota firmware to the more modern is near zero. You would have heard people saying "its broken" if there were a lot of active users. And active users tend to update firmware.

What's possible?

**Comment by BrettSheleski** [comment]
I can get you a raw dump tomorrow of what I'm getting from my Tasmota devices. 

I prefer not to update my already deployed Tasmota devices if I don't have to.

Regardless, it should be simple to include the code I had previously in addition to your alterations to handle both cases.

Also, this is a pull request in your repo. You'll have to make a pull request in my repo in order for me to merge in your changes

**Comment by diablodale** [comment]
Hahaha. Oops, wrong repro. 🤔 Yes, I will open a PR for your repro. 

When you get the raw dump, I would like to see the headers also. One code approach might be to look at the content type and use it to branch to the legacy text search // json.

**Comment by BrettSheleski** [comment]
Here's what my (legacy) Tasmota devices output (using curl):

Command: Status (used by the Poll() function)
`curl -i "http://192.168.0.51/cm?cmnd=Status"`
```
HTTP/1.1 200 OK
Content-Type: text/plain
Content-Length: 219
Connection: close
Access-Control-Allow-Origin: *

STATUS = {"Status":{"Module":1, "FriendlyName":"Basement Lights", "Topic":"basement-lights", "ButtonTopic":"0", "Power":0, "PowerOnState":3, "LedState":1, "SaveData":1, "SaveState":1, "ButtonRetain":0, "PowerRetain":0}}
```

Command: Power On
`curl -i "http://192.168.0.51/cm?cmnd=Power%20On"`
```
HTTP/1.1 200 OK
Content-Type: text/plain
Content-Length: 34
Connection: close
Access-Control-Allow-Origin: *

RESULT = {"POWER":"ON"}
POWER = ON
```

Command: Power Off
`curl -i "http://192.168.0.51/cm?cmnd=Power%20Off"`
```
HTTP/1.1 200 OK
Content-Type: text/plain
Content-Length: 36
Connection: close
Access-Control-Allow-Origin: *

RESULT = {"POWER":"OFF"}
POWER = OFF
```

I'm assuming what could be done in is to simply check for the existence of the json property of the message object.  If it exists, do what you had added, otherwise, fall back to what I had.

Something like:

```groovy
if (message?.json){ // check to see if we have json response

	if ((message?.json?.POWER in ["ON", 1, "1"]) || (message?.json?.Status?.Power in [1, "1"])) {
		setSwitchState(true);
	}
	else if ((message?.json?.POWER in ["OFF", 0, "0"]) || (message?.json?.Status?.Power in [0, "0"])) {
		setSwitchState(false);
	}

}
else{
      // fall back to "legacy" code
}
```

**Comment by diablodale** [comment]
I'm retracking this PR to open a new one on your repo + changes to code

**Comment by mestes136** [comment]
First I would like to say you guys are an inspiration, I am a 32 year old electrician from Alabama USA. I’m a very very small amount quicker than the average person but have not been to school for coding. All I’m finding is people giving me fish to eat....I want to be the fisherman though. Any advice to where I should begin? Hardware is no problem began building pc at 11...

**Comment by BrettSheleski** [comment]
If you're asking how to learn to code, there are tons of options.  I however would not pick Groovy as a language to start with though.  It is...  odd, to say the least.  Also, SmartThings' documentation is not very good.  So jumping into SmartThings' ecosystem without any prior knowledge is just not a good idea.

I'm a big proponent of having a goal and learn to accomplish that goal.  Start small, and you'll end up learning fast.  Give yourself a simple program to create, play with it, modify it, break it, and fix it.  Then go on to a slightly larger task.  Play with it, modify it, break it, fix it.  Repeat.

**Comment by mestes136** [comment]
I ordered an arduino kit from amazon today. I figured if I don’t like it it’s only $35 wasted....


Sent from Yahoo Mail for iPhone


On Tuesday, January 16, 2018, 2:30 PM, Brett Sheleski <notifications@github.com> wrote:


If you're asking how to learn to code, there are tons of options. I however would not pick Groovy as a language to start with though. It is... odd, to say the least. Also, SmartThings' documentation is not very good. So jumping into SmartThings' ecosystem without any prior knowledge is just not a good idea.

I'm a big proponent of having a goal and learn to accomplish that goal. Start small, and you'll end up learning fast. Give yourself a simple program to create, play with it, modify it, break it, and fix it. Then go on to a slightly larger task. Play with it, modify it, break it, fix it. Repeat.

**Pull request closed without merging**
